/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export declare namespace capnp_serialization {
  export function writeLineCollection(filePath: string, jsonStr: string): void
  export function writeAgencyCollection(filePath: string, jsonStr: string): void
  export function writeNodeCollection(filePath: string, jsonStr: string): void
  export function writePathCollection(filePath: string, jsonStr: string): void
  export function writeScenarioCollection(filePath: string, jsonStr: string): void
  export function writeServiceCollection(filePath: string, jsonStr: string): void
  export function writeLineObject(cacheDirectoryPath: string, jsonStr: string): void
  export function writeNodeObject(cacheDirectoryPath: string, jsonStr: string): void
}
