/*
 * Copyright 2022, Polytechnique Montreal and contributors
 *
 * This file is licensed under the MIT License.
 * License text available at https://opensource.org/licenses/MIT
 */
import { activities } from '../lookups';

// activities are standard OD trip activities.
// for each osm POI tag, this mapping will return an array of compatible OD activities

const mappings: { [key: string]: { [key: string]: string[] } } = {
    _aggregate: {
        _default: [
            'workUsual',
            'workNonUsual',
            'schoolUsual',
            'schoolNonUsual',
            'shopping',
            'service',
            'leisure',
            'visitingFriends',
            'restaurant',
            'medical',
            'worship',
            'other'
        ]
    },

    craft: {
        _default: ['workUsual', 'workNonUsual', 'service', 'other'],
        builder: ['workUsual', 'workNonUsual', 'service', 'other'],
        construction: ['workUsual', 'workNonUsual', 'service', 'other'],
        metal_construction: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        hvac: ['workUsual', 'workNonUsual', 'service', 'other'],
        electrician: ['workUsual', 'workNonUsual', 'service', 'other'],
        carpenter: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cleaning: ['workUsual', 'workNonUsual', 'service', 'other'],
        printer: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        electronics_repair: ['workUsual', 'workNonUsual', 'service', 'other'],
        plumber: ['workUsual', 'workNonUsual', 'service', 'other'],
        caterer: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        gardener: ['workUsual', 'workNonUsual', 'service', 'other'],
        photographic_laboratory: ['workUsual', 'workNonUsual', 'service', 'other'],
        photographer: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        roofer: ['workUsual', 'workNonUsual', 'service', 'other'],
        floorer: ['workUsual', 'workNonUsual', 'service', 'other'],
        shoemaker: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        dressmaker: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        signmaker: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        glaziery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        brewery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        hydraulics: ['workUsual', 'workNonUsual', 'service', 'other'],
        welder: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        automation: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        clockmaker: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        concrete: ['workUsual', 'workNonUsual', 'service', 'other'],
        cutting: ['workUsual', 'workNonUsual', 'service', 'other'],
        games: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        graphic_design: ['workUsual', 'workNonUsual', 'service', 'other'],
        industrial_equipment: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        metal_works: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        plating: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bookbinder: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        snow_removal: ['workUsual', 'workNonUsual', 'service', 'other'],
        landscaping: ['workUsual', 'workNonUsual', 'service', 'other'],
        masonry: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        mason: ['workUsual', 'workNonUsual', 'service', 'other'],
        security: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        septic_system: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        tool_repair: ['workUsual', 'workNonUsual', 'service', 'other'],
        web_design: ['workUsual', 'workNonUsual', 'service', 'other'],
        telecom: ['workUsual', 'workNonUsual', 'service', 'other'],
        trailers: ['workUsual', 'workNonUsual', 'service', 'other'],
        fiberglass: ['workUsual', 'workNonUsual', 'service', 'other'],
        garage_doors: ['workUsual', 'workNonUsual', 'service', 'other'],
        printing: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        furniture: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        adhesives: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        pumps: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        water_treatment: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        asphalt: ['workUsual', 'workNonUsual', 'service', 'other'],
        finger_printing: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        waste_management: ['workUsual', 'workNonUsual', 'service', 'other'],
        trophee: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        trophees: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        stamps: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        sharpening: ['workUsual', 'workNonUsual', 'service', 'other'],
        canvas: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        excavation: ['workUsual', 'workNonUsual', 'service', 'other'],
        handrails: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        stairs: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        design: ['workUsual', 'workNonUsual', 'service', 'other'],
        cement: ['workUsual', 'workNonUsual', 'service', 'other'],
        environment: ['workUsual', 'workNonUsual', 'service', 'other'],
        land_surveyors: ['workUsual', 'workNonUsual', 'service', 'other'],
        land_surveyor: ['workUsual', 'workNonUsual', 'service', 'other'],
        coating: ['workUsual', 'workNonUsual', 'service', 'other'],
        sanitary: ['workUsual', 'workNonUsual', 'service', 'other'],
        weighting: ['workUsual', 'workNonUsual', 'service', 'other'],
        stained_glass: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        fire_safety: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        engines: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        cranes: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        electric_motors: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        yes: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        mini_motors_repair: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        road_construction: ['workUsual', 'workNonUsual', 'service', 'other'],
        tabletops: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        hardware: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'], // should be shop=hardware
        airplane_fuel: ['workUsual', 'workNonUsual', 'service', 'other'],
        screen_printer: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        gutters: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        motors: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        fences: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        boatbuilder: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        beekeeper: ['workUsual', 'workNonUsual', 'service'],
        sawmill: ['workUsual', 'workNonUsual', 'service']
    },

    office: {
        _default: ['workUsual', 'workNonUsual', 'service', 'other'],
        educational_institution: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'other'],
        guide: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        harbour_master: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        medical: ['workUsual', 'workNonUsual', 'medical', 'service', 'other'],
        religion: ['workUsual', 'workNonUsual', 'leisure', 'service', 'worship', 'other'],
        research: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'other', 'service'],
        government: ['workUsual', 'workNonUsual', 'service', 'other'],
        ngo: ['workUsual', 'workNonUsual', 'service', 'other'],
        quango: ['workUsual', 'workNonUsual', 'service', 'other'],
        political_party: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        company: ['workUsual', 'workNonUsual', 'service', 'other'],
        accountant: ['workUsual', 'workNonUsual', 'service', 'other'],
        yes: ['workUsual', 'workNonUsual', 'service', 'other'],
        foundation: ['workUsual', 'workNonUsual', 'service', 'other'],
        financial_advisor: ['workUsual', 'workNonUsual', 'service', 'other'],
        notary: ['workUsual', 'workNonUsual', 'service', 'other'],
        consulting: ['workUsual', 'workNonUsual', 'service', 'other'],
        architect: ['workUsual', 'workNonUsual', 'service', 'other'],
        telecommunication: ['workUsual', 'workNonUsual', 'service', 'other'],
        newspaper: ['workUsual', 'workNonUsual', 'service', 'other'],
        estate_agent: ['workUsual', 'workNonUsual', 'service', 'other'],
        lawyer: ['workUsual', 'workNonUsual', 'service', 'other'],
        insurance: ['workUsual', 'workNonUsual', 'service', 'other'],
        tax_advisor: ['workUsual', 'workNonUsual', 'service', 'other'],
        consultancy: ['workUsual', 'workNonUsual', 'service', 'other'],
        advertising_agency: ['workUsual', 'workNonUsual', 'service', 'other'],
        construction: ['workUsual', 'workNonUsual', 'service', 'other'],
        hydraulics: ['workUsual', 'workNonUsual', 'service', 'other'],
        graphic_design: ['workUsual', 'workNonUsual', 'service', 'other'],
        it: ['workUsual', 'workNonUsual', 'service', 'other'],
        employment_agency: ['workUsual', 'workNonUsual', 'service', 'other'],
        coworking: ['workUsual', 'workNonUsual', 'service', 'other'],
        construction_company: ['workUsual', 'workNonUsual', 'service', 'other'],
        association: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        water_utility: ['workUsual', 'workNonUsual', 'service', 'other'],
        transport: ['workUsual', 'workNonUsual', 'service', 'other'],
        urbanist: ['workUsual', 'workNonUsual', 'service', 'other'],
        charity: ['workUsual', 'workNonUsual', 'service', 'other'],
        financial: ['workUsual', 'workNonUsual', 'service', 'other'],
        finance: ['workUsual', 'workNonUsual', 'service', 'other'],
        bailiff: ['workUsual', 'workNonUsual', 'service', 'other'],
        electricity: ['workUsual', 'workNonUsual', 'service', 'other'],
        energy_supplier: ['workUsual', 'workNonUsual', 'service', 'other'],
        distribution: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        airlines: ['workUsual', 'workNonUsual', 'service', 'other'],
        airline: ['workUsual', 'workNonUsual', 'service', 'other'],
        gaz_cleaning: ['workUsual', 'workNonUsual', 'service', 'other'],
        therapist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        security: ['workUsual', 'workNonUsual', 'service', 'other'],
        appraisal: ['workUsual', 'workNonUsual', 'service', 'other'],
        moving_company: ['workUsual', 'workNonUsual', 'service', 'other'],
        moving: ['workUsual', 'workNonUsual', 'service', 'other'],
        business_management: ['workUsual', 'workNonUsual', 'service', 'other'],
        forestry: ['workUsual', 'workNonUsual', 'service', 'other']
    },

    highway: {
        _default: [],
        services: ['workUsual', 'workNonUsual', 'restaurant', 'shopping', 'service', 'other'],
        rest_area: ['workUsual', 'workNonUsual', 'restaurant', 'shopping', 'service', 'other'],
        bus_stop: []
    },

    shop: {
        _default: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bakery: ['workUsual', 'workNonUsual', 'shopping', 'restaurant', 'other'],
        pastry: ['workUsual', 'workNonUsual', 'shopping', 'restaurant', 'other'],
        coffee: ['workUsual', 'workNonUsual', 'shopping', 'restaurant', 'other'],
        farm: ['workUsual', 'workNonUsual', 'shopping', 'leisure', 'restaurant', 'other'],
        ice_cream: ['workUsual', 'workNonUsual', 'shopping', 'restaurant', 'other'],
        mall: [], // malls should have separate shops with their entrances inside or on the building perimeter
        wholesale: ['workUsual', 'workNonUsual', 'shopping', 'restaurant', 'leisure', 'service', 'other'],
        beauty: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        massage: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        medical_supply: ['workUsual', 'workNonUsual', 'shopping', 'service', 'medical', 'other'],
        art: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        craft: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'shopping', 'service', 'leisure', 'other'],
        games: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        video_games: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        video: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        anime: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        books: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        funeral_directors: ['workUsual', 'workNonUsual', 'service', 'leisure', 'worship', 'other'],
        religion: ['workUsual', 'workNonUsual', 'service', 'shopping', 'leisure', 'worship', 'other'],
        supermarket: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        butcher: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        laundry: ['workUsual', 'workNonUsual', 'service', 'other'],
        convenience: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        outdoor: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bicycle: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        car: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        alcohol: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        motorcycle: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        optician: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        car_repair: ['workUsual', 'workNonUsual', 'service', 'other'],
        clothes: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        interior_decoration: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        shoes: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        furniture: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        mobile_phone: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        toys: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        hairdresser: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        department_store: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        doityourself: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        copyshop: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        dry_cleaning: ['workUsual', 'workNonUsual', 'service', 'other'],
        tattoo: ['workUsual', 'workNonUsual', 'service', 'other'],
        variety_store: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        car_parts: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        florist: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        pet_grooming: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        computer: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        pest_control: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        pawnbroker: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        sports: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bed: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bathroom_furnishing: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        houseware: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        musical_instrument: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        appliance: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        greengrocer: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        grocery: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        food: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        deli: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        music: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        jewelry: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        gift: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        travel_agency: ['workUsual', 'workNonUsual', 'service', 'other'],
        hardware: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        stationery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        garden_furniture: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        electronics: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        lamps: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        gas: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        pet: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        beverages: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        tyres: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        kitchen: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        chocolate: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        fabric: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        frame: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        radiotechnics: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        vacuum_cleaner: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        swimming_pool: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        paint: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        rental: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        wine: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        carpet: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        nutrition_supplements: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        locksmith: ['workUsual', 'workNonUsual', 'service', 'other'],
        health_food: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        mattress: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        tiles: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        money_lender: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        windows: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        lighting: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        electrical: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        garden_centre: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        beauty_care: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        erotic: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        storage_rental: ['workUsual', 'workNonUsual', 'service', 'other'],
        fireplace: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cannabis: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        cleaning_products: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        tea: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        scuba_diving: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        tailor: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cosmetics: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        boat: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cheese: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        motorcycle_repair: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        antiques: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        flooring: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        wheelchairs: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        perfumery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        lawn_mower: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        confectionery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        'e-cigarette': ['workUsual', 'workNonUsual', 'shopping', 'other'],
        baby_goods: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        party: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        second_hand: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        farm_equipment: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        caravan: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        trade: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        country_store: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        hairdresser_supply: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        massage_equipment: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        distribution: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        fashion_accessories: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        bag: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        bags: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        lottery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        fire_safety: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cleaning: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        window_blind: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        heating_equipment: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        water: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        hifi: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        industrial_equipment: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        model: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        military_surplus: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        trophy: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        trophee: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        trophees: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        lifts: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        agrarian: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        barbecue: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        printer_ink: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        yes: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        vacant: []
    },

    water: {
        lock: ['workNonUsual']
    },

    tourism: {
        _default: ['leisure'],
        aquarium: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'other'],
        artwork: ['leisure'],
        apartment: ['leisure', 'other', 'visitingFriends'],
        camp_site: ['leisure', 'other', 'visitingFriends'],
        caravan_site: ['leisure', 'other', 'visitingFriends'],
        camp_pitch: ['leisure', 'other', 'visitingFriends'],
        guest_house: ['leisure', 'other', 'visitingFriends'],
        chalet: ['leisure', 'other', 'visitingFriends'],
        gallery: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        hostel: ['workUsual', 'workNonUsual', 'visitingFriends', 'restaurant', 'leisure', 'service', 'other'],
        hotel: ['workUsual', 'workNonUsual', 'visitingFriends', 'restaurant', 'leisure', 'service', 'other'],
        motel: ['workUsual', 'workNonUsual', 'visitingFriends', 'leisure', 'service', 'other'],
        information: [], // see information: office
        museum: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        picnic_site: ['leisure'],
        theme_park: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        viewpoint: ['leisure'],
        wilderness_hut: ['leisure', 'other', 'visitingFriends'],
        zoo: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        attraction: ['workUsual', 'workNonUsual', 'leisure'],
        yes: ['leisure']
    },

    club: {
        sport: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        shooting: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        social: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other']
    },

    healthcare: {
        _default: ['workUsual', 'workNonUsual', 'medical', 'other'],
        pharmacy: ['workUsual', 'workNonUsual', 'shopping', 'service', 'medical', 'other'],
        clinic: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        doctor: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        hospital: ['workUsual', 'workNonUsual', 'service', 'medical', 'visitingFriends', 'other'],
        dentist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        optometrist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        yes: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        laboratory: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        alternative: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        physiotherapist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        psychotherapist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        podiatrist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        audiologist: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        hospice: ['workUsual', 'workNonUsual', 'medical', 'other']
    },

    amenity: {
        _default: ['workUsual', 'workNonUsual', 'other'],
        parking_entrance: [],
        bar: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        bbq: ['leisure'],
        biergarten: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        cafe: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        fast_food: ['workUsual', 'workNonUsual', 'restaurant', 'other'],
        food_court: ['workUsual', 'workNonUsual', 'restaurant', 'other'],
        ice_cream: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        pub: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        restaurant: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        college: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        driving_school: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'other'],
        kindergarten: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        language_school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        library: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        toy_library: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        music_school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        theatre_school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'leisure', 'other'],
        university: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        bicycle_rental: ['workUsual', 'workNonUsual', 'service', 'other'],
        boat_rental: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        boat_sharing: ['service', 'leisure', 'other'],
        bus_station: ['workUsual', 'workNonUsual', 'other'],
        car_rental: ['workUsual', 'workNonUsual', 'service', 'other'],
        helicopter_rental: ['workUsual', 'workNonUsual', 'service', 'other'],
        car_sharing: ['service'],
        car_wash: ['workUsual', 'workNonUsual', 'service', 'other'],
        vehicle_inspection: ['workUsual', 'workNonUsual', 'service', 'other'],
        ferry_terminal: ['workUsual', 'workNonUsual', 'service', 'other'],
        fuel: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        taxi: ['workUsual', 'workNonUsual', 'service', 'other'],
        atm: ['service'],
        bank: ['workUsual', 'workNonUsual', 'service', 'other'],
        bureau_de_change: ['workUsual', 'workNonUsual', 'service', 'other'],
        baby_hatch: ['workUsual', 'workNonUsual', 'service', 'medical', 'other'],
        clinic: ['workUsual', 'workNonUsual', 'service', 'schoolNonUsual', 'medical', 'other'],
        dentist: ['workUsual', 'workNonUsual', 'service', 'schoolNonUsual', 'medical', 'other'],
        doctors: ['workUsual', 'workNonUsual', 'service', 'schoolNonUsual', 'medical', 'other'],
        hospital: [
            'workUsual',
            'workNonUsual',
            'service',
            'schoolUsual',
            'visitingFriends',
            'schoolNonUsual',
            'medical',
            'other'
        ],
        nursing_home: ['workUsual', 'workNonUsual', 'service', 'schoolNonUsual', 'visitingFriends', 'medical', 'other'],
        pharmacy: ['workUsual', 'workNonUsual', 'shopping', 'service', 'medical', 'other'],
        social_facility: [
            'workUsual',
            'workNonUsual',
            'service',
            'schoolNonUsual',
            'visitingFriends',
            'medical',
            'other'
        ],
        veterinary: ['workUsual', 'workNonUsual', 'service', 'schoolNonUsual', 'other'],
        arts_centre: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        brothel: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        casino: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        cinema: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        community_centre: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        fountain: [],
        gambling: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        nightclub: ['workUsual', 'workNonUsual', 'restaurant', 'leisure', 'other'],
        planetarium: ['workUsual', 'workNonUsual', 'shopping', 'schoolNonUsual', 'leisure', 'other'],
        public_bookcase: ['service', 'leisure'],
        social_centre: ['workUsual', 'workNonUsual', 'medical', 'service', 'leisure', 'other'],
        stripclub: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        studio: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        swingerclub: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        theatre: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        animal_boarding: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        animal_shelter: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        animal_training: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        baking_oven: ['service', 'leisure'],
        childcare: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        conference_center: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        courthouse: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'other'],
        crematorium: ['workUsual', 'workNonUsual', 'service', 'other'],
        dive_centre: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        embassy: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        fire_station: ['workUsual', 'workNonUsual', 'other'],
        firepit: [], // deprecated
        grave_yard: ['worship', 'other'],
        gym: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'], // deprecated
        hunting_stand: ['leisure'],
        internet_cafe: ['workUsual', 'workNonUsual', 'restaurant', 'service', 'leisure', 'other'],
        kitchen: ['workUsual', 'workNonUsual', 'restaurant', 'service', 'leisure', 'other'],
        kneipp_water_cure: ['workUsual', 'workNonUsual', 'service', 'medical', 'leisure', 'other'],
        marketplace: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'other'],
        monastery: ['workUsual', 'workNonUsual', 'shopping', 'service', 'leisure', 'worship', 'other'],
        photo_booth: ['shopping', 'service', 'leisure'],
        place_of_worship: ['workUsual', 'workNonUsual', 'service', 'leisure', 'worship', 'other'],
        police: ['workUsual', 'workNonUsual', 'service', 'other'],
        post_box: [],
        post_depot: ['workUsual', 'workNonUsual', 'service', 'other'],
        post_office: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        prison: ['workUsual', 'workNonUsual', 'visitingFriends', 'other'],
        public_bath: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        public_building: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'], // deprecated
        ranger_station: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        recycling: [],
        sanitary_dump_station: ['service'],
        sauna: ['workUsual', 'workNonUsual', 'service', 'leisure', 'medical', 'other'], // deprecated
        shelter: [],
        shower: [],
        telephone: [],
        toilets: [],
        private_toilet: [],
        townhall: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        vending_machine: ['workNonUsual', 'shopping'],
        waste_basket: [],
        waste_disposal: ['service'],
        waste_transfer_station: ['service'],
        watering_place: [],
        water_point: ['service'],
        parking: [],
        bench: [],
        parking_space: [],
        bicycle_parking: [],
        drinking_water: [],
        clock: [],
        motorcycle_parking: [],
        mobile_money_agent: ['service'],
        swimming_pool: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        events_venue: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        loading_dock: ['workUsual', 'workNonUsual', 'service', 'other'],
        compressed_air: ['service'],
        payment_terminal: [],
        dojo: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        money_transfer: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        animal_breeding: ['workUsual', 'workNonUsual', 'service', 'other'],
        boat_storage: ['workNonUsual', 'service'],
        letter_box: [],
        game_feeding: ['leisure'],
        love_hotel: ['workUsual', 'workNonUsual', 'service', 'restaurant', 'leisure', 'other'],
        lavoir: ['service'],
        training: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        feeding_place: [],
        weighbridge: ['workUsual', 'workNonUsual', 'service'],
        shop: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        ticket_validator: [],
        office: ['workUsual', 'workNonUsual', 'service', 'other'],
        smoking_area: [],
        coworking_space: ['workUsual', 'workNonUsual', 'other', 'service'],
        prep_school: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'other'],
        yes: [],
        stables: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        reception_desk: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        trolley_bay: [],
        mortuary: ['workUsual', 'workNonUsual', 'service', 'other'],
        garages: ['workUsual', 'workNonUsual', 'service', 'other'],
        water: [], // wrong tag : mistake
        register_office: ['workUsual', 'workNonUsual', 'service', 'other'],
        car_pooling: [],
        public_hall: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        research_institute: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        payment_centre: ['workUsual', 'workNonUsual', 'service', 'other'],
        camping: ['leisure', 'visitingFriends', 'other'],
        customs: ['workUsual', 'workNonUsual', 'service', 'other'],
        table: [],
        refugee_housing: ['workUsual', 'workNonUsual', 'visitingFriends', 'service', 'other'],
        spa: ['workUsual', 'workNonUsual', 'service', 'other', 'leisure'], // do not use: ambiguous
        retirement_home: ['workUsual', 'workNonUsual', 'service', 'leisure', 'visitingFriends', 'other'],
        vacuum_cleaner: [],
        hookah_lounge: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        sanatorium: ['workUsual', 'workNonUsual', 'service', 'other', 'leisure'], // do not use: ???
        karaoke_box: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        workshop: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'shopping', 'service', 'leisure', 'other'],
        vehicle_ramp: [],
        social_club: ['workUsual', 'workNonUsual', 'leisure', 'restaurant', 'other'],
        nameplate: [],
        polling_station: ['workUsual', 'workNonUsual', 'service', 'other'],
        club: ['workUsual', 'workNonUsual', 'service', 'restaurant', 'leisure', 'other'],
        community_hall: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        picnic_table: [],
        public_service: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        dancing_school: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        music_venue: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        ski_school: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        temple: ['workUsual', 'workNonUsual', 'worship', 'leisure', 'other'],
        funeral_home: ['workUsual', 'workNonUsual', 'worship', 'service', 'other'],
        ski_rental: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        canteen: ['workUsual', 'workNonUsual', 'restaurant', 'other'],
        dressing_room: ['service'],
        storage: ['service'],
        exhibition_centre: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'shopping', 'service', 'other'],
        auditorium: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        concert_hall: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        greenhouse: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        nursery: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        public_facility: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        healthcare: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'medical', 'other'],
        luggage_locker: ['service'],
        boathouse: [],
        garage: [],
        administration: ['workUsual', 'workNonUsual', 'service', 'other'],
        border_control: ['workUsual', 'workNonUsual', 'service', 'other'],
        device_charging_station: [],
        market: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        health_facility: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'medical', 'other'],
        construction: ['workNonUsual', 'other'],
        harbourmaster: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        scrapyard: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        education: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        coast_guard: ['workUsual', 'workNonUsual', 'service', 'other'],
        hospice: ['workUsual', 'workNonUsual', 'service', 'medical', 'visitingFriends', 'other'],
        vacant: [],
        warehouse: ['workUsual', 'workNonUsual', 'service', 'other'],
        student_accommodation: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'other'],
        church: ['workUsual', 'workNonUsual', 'service', 'leisure', 'worship', 'other'],
        self_storage: ['workNonUsual', 'service'],
        youth_centre: ['workUsual', 'workNonUsual', 'service', 'leisure', 'visitingFriends', 'other'],
        archive: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        piano: ['leisure'],
        financial_advice: ['workUsual', 'workNonUsual', 'service', 'other'],
        industrial: ['workUsual', 'workNonUsual', 'service', 'shopping', 'other'],
        health_centre: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'medical', 'other'],
        care_home: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'medical', 'other'],
        community_center: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        car_repair: ['workUsual', 'workNonUsual', 'service', 'other'],
        public_office: ['workUsual', 'workNonUsual', 'service', 'other'],
        garden: ['workUsual', 'workNonUsual', 'service', 'leisure', 'shopping', 'other'],
        service: ['workUsual', 'workNonUsual', 'service', 'other'],
        charging_station: [],
        art_school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        recreation_ground: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        snow_disposal: ['workUsual', 'workNonUsual'],
        proposed: [],
        fridge: [],
        refugee_site: ['workNonUsual', 'other']
    },

    building: {
        _default: [],
        apartments: ['visitingFriends'],
        bungalow: ['visitingFriends'],
        cabin: ['visitingFriends'],
        detached: ['visitingFriends'],
        dormitory: ['visitingFriends'],
        farm: ['workUsual', 'workNonUsual', 'visitingFriends', 'shopping', 'service', 'other'],
        ger: ['visitingFriends'],
        hotel: ['workUsual', 'workNonUsual', 'service', 'visitingFriends', 'leisure', 'restaurant', 'other'],
        house: ['visitingFriends'],
        houseboat: ['visitingFriends'],
        residential: ['visitingFriends'],
        semidetached_house: ['visitingFriends'],
        static_caravan: ['visitingFriends'],
        terrace: ['visitingFriends'],
        commercial: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'], // only if there is at least a shop/main entrance and no shop/craft/office... point inside
        industrial: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'], // only if there is at least a shop/main entrance and no shop/craft/office... point inside
        kiosk: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        office: ['workUsual', 'workNonUsual', 'service', 'other'], // only if there is at least a shop/main entrance and no shop/craft/office... point inside
        retail: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'], // only if there is at least a shop/main entrance and no shop/craft/office... point inside
        supermarket: ['workUsual', 'workNonUsual', 'shopping', 'other'],
        warehouse: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        cathedral: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        chapel: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        church: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        mosque: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        religious: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        shrine: ['workNonUsual', 'leisure', 'worship', 'other'],
        temple: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        synagogue: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        bakehouse: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        civic: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        fire_station: ['workUsual', 'workNonUsual', 'other'],
        government: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'service', 'other'],
        hospital: [
            'workUsual',
            'workNonUsual',
            'schoolUsual',
            'schoolNonUsual',
            'visitingFriends',
            'service',
            'medical',
            'other'
        ],
        kindergarten: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'other'],
        public: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        school: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'leisure', 'other'],
        toilets: ['workNonUsual'],
        train_station: ['workUsual', 'workNonUsual', 'service', 'other'],
        transportation: ['workUsual', 'workNonUsual', 'service', 'other'],
        college: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'leisure', 'service', 'other'],
        university: ['workUsual', 'workNonUsual', 'schoolUsual', 'schoolNonUsual', 'service', 'leisure', 'other'],
        barn: ['workUsual', 'workNonUsual'],
        conservatory: ['workUsual', 'workNonUsual'],
        cowshed: ['workUsual', 'workNonUsual'],
        farm_auxiliary: ['workUsual', 'workNonUsual'],
        greenhouse: ['workUsual', 'workNonUsual'],
        stable: ['workUsual', 'workNonUsual'],
        sty: ['workUsual', 'workNonUsual'],
        grandstand: ['workNonUsual', 'leisure', 'other'],
        pavilion: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        riding_hall: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        sports_hall: ['workUsual', 'workNonUsual', 'leisure', 'service', 'other'],
        stadium: ['workUsual', 'workNonUsual', 'leisure', 'shopping', 'service', 'other'],
        hangar: ['workUsual', 'workNonUsual', 'service', 'other'],
        hut: [],
        shed: [],
        carport: [],
        garage: [],
        garages: ['workUsual', 'workNonUsual', 'service', 'other'],
        parking: ['workNonUsual'],
        digester: ['workUsual', 'workNonUsual'],
        service: ['workNonUsual'],
        transformer_tower: ['workNonUsual'],
        water_tower: ['workNonUsual'],
        bunker: ['workNonUsual'],
        bridge: ['workUsual', 'workNonUsual'],
        construction: ['workNonUsual'],
        roof: ['leisure', 'other'],
        ruins: [],
        yes: [],
        tower: [],
        abandoned: [],
        shelter: []
    },

    camping: {
        reception: ['workUsual', 'workNonUsual', 'leisure', 'service', 'shopping', 'other']
    },

    industrial: {
        _default: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        distributor: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        distribution: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        warehouse: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other']
    },

    emergency: {
        _default: [],
        ambulance_station: ['workUsual', 'workNonUsual'],
        lifeguard: ['workUsual', 'workNonUsual'],
        lifeguard_base: ['workUsual', 'workNonUsual'],
        lifeguard_tower: ['workUsual', 'workNonUsual'],
        lifeguard_platform: ['workUsual', 'workNonUsual'],
        fire_hydrant: [],
        phone: [],
        no: []
    },

    geological: {
        palaeontological_site: ['workUsual', 'workNonUsual', 'leisure']
    },

    telecom: {
        _default: [],
        data_center: ['workUsual', 'workNonUsual', 'service', 'other'],
        service_device: ['workNonUsual'],
        exchange: ['workNonUsual']
    },

    waterway: {
        _default: [],
        dock: ['workUsual', 'workNonUsual', 'service', 'other'],
        boatyard: ['workUsual', 'workNonUsual', 'service', 'other'],
        fuel: ['workUsual', 'workNonUsual', 'shopping', 'service', 'other'],
        dam: ['workUsual', 'workNonUsual'],
        lock_gate: ['workUsual', 'workNonUsual']
    },

    historic: {
        _default: ['leisure'],
        aqueduct: ['workNonUsual', 'leisure'],
        battlefield: ['workNonUsual', 'leisure'],
        cannon: ['leisure'],
        castle_wall: ['workNonUsual', 'leisure'],
        city_gate: ['workNonUsual', 'leisure'],
        citywalls: ['workNonUsual', 'leisure'],
        archaeological_site: ['workUsual', 'workNonUsual', 'leisure'],
        memorial: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        ruins: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        monument: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        pillory: ['leisure'],
        building: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        castle: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        bridge: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        industrial: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        ship: ['leisure'],
        tank: ['leisure'],
        tomb: ['leisure', 'worship'],
        wreck: ['leisure'],
        railway_car: ['leisure'],
        aircraft: ['leisure'],
        tower: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        heritage: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        manor: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        fort: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        wayside_chapel: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        church: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        monastery: ['workUsual', 'workNonUsual', 'leisure', 'worship', 'other'],
        farm: ['workUsual', 'workNonUsual', 'leisure', 'shopping', 'other'],
        wayside_shrine: [],
        locomotive: ['leisure'],
        yes: ['leisure']
    },

    information: {
        _default: [],
        office: ['workUsual', 'workNonUsual', 'leisure', 'other']
    },

    leisure: {
        _default: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        bird_hide: ['leisure'],
        common: ['leisure'],
        firepit: ['leisure'],
        nature_reserve: ['workNonUsual', 'leisure'],
        picnic_table: [],
        slipway: ['leisure'],
        playground: ['workNonUsual', 'leisure'],
        swimming_pool: ['workNonUsual', 'leisure'],
        sports_centre: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        fitness_centre: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        ice_rink: ['workNonUsual', 'leisure'],
        fishing: ['leisure'],
        pitch: ['workNonUsual', 'leisure'],
        park: ['workNonUsual', 'leisure'],
        dance: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        swimming_area: ['leisure'],
        golf_course: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        miniature_golf: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        water_park: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        summer_camp: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        garden: ['workUsual', 'workNonUsual', 'service', 'leisure', 'shopping', 'other'],
        amusement_arcade: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        stadium: ['workUsual', 'workNonUsual', 'service', 'leisure', 'shopping', 'other'],
        escape_game: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        track: ['leisure'],
        dog_park: ['workNonUsual', 'leisure'],
        marina: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        fitness_station: ['leisure', 'other'],
        paddling_pool: ['leisure'],
        bleachers: ['leisure'],
        horse_riding: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other'],
        recreation_ground: ['leisure'],
        splash_pad: ['workNonUsual', 'leisure'],
        disc_golf_course: ['workUsual', 'workNonUsual', 'leisure'],
        beach_resort: ['workUsual', 'workNonUsual', 'leisure'],
        bowling_alley: ['workUsual', 'workNonUsual', 'leisure'],
        bandstand: ['workNonUsual', 'leisure']
    },

    man_made: {
        _default: [],
        lighthouse: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        observatory: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'schoolUsual', 'leisure', 'other'],
        pumping_station: ['workNonUsual'],
        telescope: ['workUsual', 'workNonUsual', 'schoolNonUsual', 'schoolUsual', 'leisure', 'other'],
        watermill: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        wastewater_plant: ['workUsual', 'workNonUsual'],
        water_works: ['workUsual', 'workNonUsual'],
        windmill: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        works: ['workUsual', 'workNonUsual'],
        storage_tank: [],
        tower: ['workNonUsual'],
        yes: [],
        surveillance: [],
        flagpole: [],
        street_cabinet: ['workNonUsual'],
        monitoring_station: ['workNonUsual'],
        silo: [],
        bridge: [],
        pier: [],
        petroleum_well: ['workNonUsual'],
        communications_tower: ['workNonUsual'],
        obelisk: ['workNonUsual', 'leisure'],
        dovecote: ['workNonUsual'],
        gasometer: ['workNonUsual'],
        kiln: ['workNonUsual'],
        mineshaft: ['workNonUsual'],
        reservoir_covered: ['workNonUsual'],
        water_tower: ['workNonUsual']
    },

    military: {
        _default: [],
        barracks: ['workUsual', 'workNonUsual'],
        office: ['workUsual', 'workNonUsual', 'service', 'other'],
        airfield: ['workUsual', 'workNonUsual'],
        bunker: ['workUsual', 'workNonUsual'],
        checkpoint: ['workUsual', 'workNonUsual', 'service', 'other'],
        naval_base: ['workUsual', 'workNonUsual'],
        training_area: ['workUsual', 'workNonUsual'],
        obstacle_course: ['workNonUsual'],
        range: ['workNonUsual']
    },

    power: {
        _default: [],
        plant: ['workUsual', 'workNonUsual'],
        substation: ['workUsual', 'workNonUsual'],
        generator: ['workNonUsual']
    },

    public_transport: {
        _default: [],
        station: ['workUsual', 'workNonUsual', 'service', 'other'],
        stop_position: [],
        platform: []
    },

    railway: {
        _default: [],
        station: ['workUsual', 'workNonUsual', 'service', 'other'],
        turntable: ['workUsual', 'workNonUsual'],
        roundhouse: ['workUsual', 'workNonUsual'],
        wash: ['workUsual', 'workNonUsual'],
        vehicle_depot: ['workUsual', 'workNonUsual'],
        subway_entrance: ['workNonUsual', 'service'],
        stop: [],
        platform: []
    },

    landuse: {
        _default: [],
        quarry: ['workUsual', 'workNonUsual', 'service'],
        landfill: ['workUsual', 'workNonUsual', 'service'],
        cemetery: ['workUsual', 'workNonUsual', 'service', 'leisure', 'worship', 'other'],
        allotments: ['workNonUsual', 'service', 'leisure', 'other'],
        depot: ['workNonUsual', 'other'],
        military: ['workUsual', 'workNonUsual'],
        recreation_ground: ['workNonUsual', 'leisure'],
        religious: ['workUsual', 'workNonUsual', 'worship', 'leisure', 'other'],
        winter_sports: ['workNonUsual', 'leisure'],
        mine: ['workUsual', 'workNonUsual'],
        apiary: ['workUsual', 'workNonUsual'],
        garden: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        tourism: ['workUsual', 'workNonUsual', 'leisure', 'other'],
        leisure: ['workNonUsual', 'leisure', 'other']
    },

    golf: {
        _default: [],
        clubhouse: ['workUsual', 'workNonUsual', 'service', 'leisure', 'other']
    }
};

// verify activities (make sure that it would never output non-existing/incorrect/nonstandard activities):
for (const key in mappings) {
    for (const subKey in mappings[key]) {
        const activityValues = mappings[key][subKey];
        for (let i = 0, count = activityValues.length; i < count; i++) {
            if (!activities.includes(activityValues[i])) {
                console.error(
                    `ERROR: non-existing activity in mappings js file: ${key}.${subKey}[${activityValues[i]}]`
                );
            }
        }
    }
}

export default mappings;

/*
TODO: remove these comments and replace by real documentation + make it up to date:

Procedure:

- export a nodes geojson file from overpass
  - include entrances and buildings + ways
- export a polygons + multipolygons geojson file from overpass
  - include entrances and buildings + ways
- read geojson file from overpass (TODO: stream read for large files)
- create an empty locations array
- create an array for all entrances
- calculate centroids and areas of all polygons (include relations for multipolygons)
- create a geojson collection of all entrances (spatially indexed)
- create a geojson collection of all points (spatially indexed, but filter using osmActivitesMapping)
- find all entrances on polygon perimeter if building, ignore if not a building (first calculate the max distance from centroid for the polygon envelope, then use the index of entrances to find entrances in the vicinity)


HERE THE REST MUST BE UPDATED, see task importLocationsFromOsmGeojson:
- from each centroid, find all points inside polygons (first calculate the max distance from centroid for the polygon envelope, then use the index of points to find entrances in the vicinity)
- for each polygon
  - if leisure and access=private: ignore
  - if no points inside and not building and area is smaller than 10000m^2, use a point on polygon contour nearest to osrm point (walking) and calculate bird distance
  - if larger than 10000m^2, trigger a warning to correct/validate with osm way/node id url
  - if distance to nearest osrm point > 50m, trigger a warning to correct/validate with osm way/node id url
  - if distance to nearest osrm point > 100m, trigger an error to correct/validate with osm way/node id url
  - add point to the locations array if no error/warning
- for each point in polygons, snap to the nearest entrance
    - if leisure and access=private: ignore
   - if no entrance, use a point on polygon contour nearest to osrm point (walking) and calculate bird distance
   - if multiple entrances, choose the one with shortest distance to osrm point
   - if entrance, find nearest osrm point (walking) and calculate bird distance
   - if distance to nearest osrm point > 50m, trigger a warning to correct/validate with osm way/node id url
   - if distance to nearest osrm point > 100m, trigger an error to correct/validate with osm way/node id url
   - add point to the locations array if no error/warning
- for each point not in polygon
  - if leisure and access=private: ignore
  - find nearest osrm point (walking) and calculate bird distance
  - if distance to nearest osrm point > 50m, trigger a warning to correct/validate with osm way/node id url
  - if distance to nearest osrm point > 100m, trigger an error to correct/validate with osm way/node id url
  - add point to the locations array if no error/warning
- merge all locations at the same coordinates (merge all tags too)
- aggregate all locations around 10m (loop until no distance < 10m), snap to first location (to make sure we stay on osrm ways)
- for each location in locations array
  - match activities using osmActivitesMapping (include all matching tags and values)
  - if not found, trigger a warning/error with tags/values
  - remove points with no activity (empty activities array)

*/
