/*
 * Copyright 2022, Polytechnique Montreal and contributors
 *
 * This file is licensed under the MIT License.
 * License text available at https://opensource.org/licenses/MIT
 */
export const categories = [
    'service',
    'craft',
    'farm',
    'government',
    'healthcare',
    'industrial',
    'leisure',
    'military',
    'office',
    'religion',
    'restaurant',
    'education',
    'shop',
    'social',
    'transport',
    'transit',
    'utility',
    'flat' // TODO: temporary until we implement residential entrances separately from POIs
] as const;

/** An enumeration of amenities categories */
export type PlaceCategory = (typeof categories)[number];

export const detailedCategoryToCategory = {
    conference_center: 'service',
    craft: 'craft',
    farm: 'farm',
    fire_station: 'government',
    government: 'government',
    healthcare_other: 'healthcare',
    healthcare_clinic: 'healthcare',
    healthcare_alternative: 'healthcare',
    healthcare_dentist: 'healthcare',
    healthcare_hospital: 'healthcare',
    hotel: 'service',
    industrial: 'industrial',
    landfill: 'industrial',
    quarry: 'industrial',
    leisure_other: 'leisure',
    leisure_park: 'leisure',
    leisure_adult: 'leisure',
    leisure_art: 'leisure',
    leisure_cinema: 'leisure',
    leisure_golf: 'leisure',
    leisure_gym: 'leisure',
    leisure_playground: 'leisure',
    leisure_sports: 'leisure',
    leisure_swimming: 'leisure',
    leisure_library: 'leisure',
    military: 'military',
    office: 'office',
    police_station: 'government',
    prison: 'government',
    public: 'government',
    religion: 'religion',
    restaurant_restaurant: 'restaurant',
    restaurant_bar: 'restaurant',
    restaurant_cafe: 'restaurant',
    restaurant_fast_food: 'restaurant',
    school_college: 'education',
    school_kindergarten: 'education',
    school_other: 'education',
    school_primary: 'education',
    school_research: 'education',
    school_secondary: 'education',
    school_university: 'education',
    service_other: 'service',
    service_atm: 'service',
    service_bank: 'service',
    service_beauty: 'service',
    service_car_repair: 'service',
    service_car_wash: 'service',
    service_fuel: 'service',
    service_funeral: 'service',
    service_hairdresser: 'service',
    service_postal: 'service',
    service_rental: 'service',
    service_storage: 'service',
    service_veterinary: 'service',
    shop_other: 'shop',
    shop_bicycle: 'shop',
    shop_car: 'shop',
    shop_clothes: 'shop',
    shop_convenience: 'shop',
    shop_department_store: 'shop',
    shop_food: 'shop',
    shop_hardware: 'shop',
    shop_pharmacy: 'shop',
    shop_supermarket: 'shop',
    social: 'social',
    tourism_tourism: 'leisure',
    tourism_camping: 'leisure',
    tourism_rental: 'leisure',
    transport: 'transport',
    transit_bus_station: 'transit',
    transit_ferry_terminal: 'transit',
    transit_train_station: 'transit',
    transit_station: 'transit',
    utility: 'utility',
    flat: 'flat' // TODO: temporary until we implement residential entrances separately from POIs
};

export const detailedCategories = Object.keys(detailedCategoryToCategory);
export type PlaceDetailedCategory = (typeof detailedCategories)[number];
