# Test that we can build the docker image on each PR. Will not push the image
name: PR Container Build Check

on:
  pull_request:
    branches: 
      - "main"

jobs:
  pr-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
